/**
 * Scholarship programmes run by governments and official agencies.
 *
 * These are not university awards and they do not live on a university domain,
 * which is why they need their own list — but they are not middlemen either.
 * A government scholarship agency publishing its own programme is the primary
 * source, in exactly the way a university publishing its own bursary is. The
 * middleman is the site that reposts it with a referral link, and that site is
 * still banned.
 *
 * The list is curated rather than crawled, because there are perhaps sixty of
 * these in the world and getting each one right matters more than finding them
 * automatically. Every entry is re-checked live on each run: if its page stops
 * responding, it stops appearing.
 *
 * The Arabic fields are here rather than in the dictionary because they belong
 * to a specific programme rather than to the interface. They are translated,
 * unlike anything read off a university's page, because these sentences are this
 * project's own summary of a programme rather than the institution's words.
 *
 * `attainable` is the judgement this whole project turns on. It is not about
 * how much money the award carries — several full rides here are far easier to
 * win than a partial award at a famous university, because they are allocated
 * by country quota rather than by competition against the whole world.
 */

export const PROGRAMMES = [
  // ---------------------------------------------------------------- attainable
  {
    id: 'stipendium-hungaricum',
    name: 'Stipendium Hungaricum',
    body: 'Tempus Public Foundation, Hungary',
    url: 'https://stipendiumhungaricum.hu/apply/',
    cc: 'HU',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Full tuition waiver, monthly stipend, accommodation contribution, medical cover',
    band: 'open-to-most',
    window: [11, 1],
    note: 'Allocated by bilateral country quota, so you compete against your own country rather than against the world. Nominated through your home country’s sending partner.',
    barNote: 'Entrance exam pass mark 56/100; no published GPA floor',
    coversAr: "إعفاء كامل من الرسوم، ومخصّص شهري، ومساهمة في السكن، وتأمين صحي",
    noteAr: "تُوزَّع بحصص ثنائية لكل دولة، فتنافس أبناء بلدك لا العالم كله. والترشيح يتم عبر الجهة الموفدة في بلدك.",
    barNoteAr: "درجة النجاح في اختبار القبول 56 من 100، ولا يُعلَن حدّ أدنى للمعدل",
    automatic: false,
  },
  {
    id: 'turkiye-burslari',
    name: 'Türkiye Bursları',
    body: 'Presidency for Turks Abroad, Türkiye',
    url: 'https://turkiyeburslari.gov.tr/',
    cc: 'TR',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Tuition, accommodation, flights, health insurance, one year of Turkish, monthly stipend',
    band: 'competitive',
    window: [1, 2],
    note: 'Large intake and country quotas. There is an interview stage, and the site publishes no grade bar.',
    coversAr: "الرسوم، والسكن، وتذاكر الطيران، والتأمين الصحي، وسنة لتعلّم التركية، ومخصّص شهري",
    noteAr: "أعداد المقبولين كبيرة والحصص موزّعة على الدول. هناك مرحلة مقابلة، ولا ينشر الموقع حدًّا أدنى للدرجات.",
    automatic: false,
  },
  {
    id: 'gks-korea',
    name: 'Global Korea Scholarship',
    body: 'NIIED, Republic of Korea',
    url: 'https://www.studyinkorea.go.kr/',
    cc: 'KR',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Airfare, one year of Korean language training, tuition, monthly allowance',
    band: 'competitive',
    window: [9, 10],
    note: 'Roughly 280 undergraduate and 2,000 graduate places a year. Embassy track and university track are separate applications.',
    barNote: 'GPA 80% or 2.64/4.0, age under 40',
    coversAr: "تذاكر الطيران، وسنة لتعلّم الكورية، والرسوم، ومخصّص شهري",
    noteAr: "نحو 280 مقعدًا للبكالوريوس و2000 للدراسات العليا سنويًا. ومسار السفارة ومسار الجامعة طلبان منفصلان.",
    barNoteAr: "معدل 80% أو 2.64 من 4، والعمر دون 40",
    automatic: false,
  },
  {
    id: 'mext-japan',
    name: 'MEXT Scholarship (Monbukagakusho)',
    body: 'Ministry of Education, Japan',
    url: 'https://www.studyinjapan.go.jp/en/planning/scholarship/',
    cc: 'JP',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Tuition exemption, monthly stipend, round-trip airfare',
    band: 'competitive',
    note: 'Selected on written subject exams rather than on your transcript, which suits people who test well more than it suits people with a perfect record. Embassy and university-recommendation routes both exist.',
    barNote: 'Age under 25 for undergraduate, under 35 for research',
    coversAr: "إعفاء من الرسوم، ومخصّص شهري، وتذكرة طيران ذهابًا وإيابًا",
    noteAr: "الاختيار يقوم على اختبارات تحريرية في المواد لا على كشف درجاتك، وهو ما يناسب من يجيد الاختبارات أكثر ممّا يناسب صاحب السجل المثالي. ولها مساران: عبر السفارة أو بترشيح من الجامعة.",
    barNoteAr: "العمر دون 25 للبكالوريوس، ودون 35 للبحث",
    automatic: false,
  },
  {
    id: 'jasso-honors',
    name: 'JASSO Monbukagakusho Honors Scholarship',
    body: 'Japan Student Services Organization',
    url: 'https://www.jasso.go.jp/en/study_j/scholarships/shoureihi/',
    cc: 'JP',
    levels: ['bachelor', 'master'],
    tier: 'stipend',
    covers: '¥48,000 a month for privately financed international students',
    band: 'open-to-most',
    note: 'The grade floor is a 2.30 GPA, which is genuinely ordinary. Your university nominates you after you enrol.',
    barNote: 'GPA 2.30, JLPT N2',
    coversAr: "48,000 ين شهريًا للطلاب الدوليين الذين يموّلون دراستهم بأنفسهم",
    noteAr: "الحدّ الأدنى للمعدل 2.30، وهو حدّ عادي فعلًا. وجامعتك هي التي ترشّحك بعد التحاقك بها.",
    barNoteAr: "معدل 2.30، ومستوى JLPT N2",
    automatic: false,
  },
  {
    id: 'taiwan-moe',
    name: 'Taiwan Scholarship',
    body: 'Ministry of Education, Taiwan',
    url: 'https://taiwanscholarship.moe.gov.tw/',
    cc: 'TW',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Up to NT$40,000 a semester of tuition, plus NT$15,000 (bachelor) or NT$20,000 (master) a month',
    band: 'competitive',
    window: [2, 3],
    note: 'Applied for at a Taiwanese overseas mission, and separately to the university itself.',
    coversAr: "حتى 40,000 دولار تايواني لكل فصل من الرسوم، إضافة إلى 15,000 (بكالوريوس) أو 20,000 (ماجستير) شهريًا",
    noteAr: "يُقدَّم لها في إحدى البعثات التايوانية في الخارج، وللجامعة نفسها بطلب منفصل.",
    automatic: false,
  },
  {
    id: 'csc-china',
    name: 'Chinese Government Scholarship',
    body: 'China Scholarship Council',
    url: 'https://www.studyinchina.edu.cn/',
    cc: 'CN',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Tuition, on-campus accommodation, monthly stipend, comprehensive medical insurance',
    band: 'competitive',
    window: [2, 4],
    note: 'Type A goes through your home embassy; Type B is applied for directly at the university, which is usually the better odds. Undergraduate applicants sit the CSCA test from 2026/27.',
    coversAr: "الرسوم، والسكن الجامعي، ومخصّص شهري، وتأمين طبي شامل",
    noteAr: "النوع A عبر سفارة بلدك، والنوع B يُقدَّم له مباشرة لدى الجامعة وهو عادة الأوفر حظًا. ومتقدّمو البكالوريوس يؤدّون اختبار CSCA اعتبارًا من 2026/27.",
    automatic: false,
  },
  {
    id: 'holland-scholarship',
    name: 'Holland Scholarship',
    body: 'Dutch Ministry of Education and participating universities',
    url: 'https://www.studyinnl.org/finances/holland-scholarship',
    cc: 'NL',
    levels: ['bachelor', 'master'],
    tier: 'fixed',
    covers: '€5,000 in the first year only',
    band: 'open-to-most',
    note: 'First year only, and it does not renew. Each university sets its own deadline; the cycle opens on 1 November.',
    coversAr: "5,000 يورو في السنة الأولى فقط",
    noteAr: "السنة الأولى فقط، ولا تتجدّد. وكل جامعة تحدّد موعدها النهائي، والدورة تُفتح في 1 نوفمبر.",
    automatic: false,
  },
  {
    id: 'vlir-uos',
    name: 'VLIR-UOS Scholarships',
    body: 'Flemish Interuniversity Council, Belgium',
    url: 'https://www.vliruos.be/en/scholarships/',
    cc: 'BE',
    levels: ['bachelor', 'master'],
    tier: 'full-ride',
    covers: 'Tuition, living allowance, travel, insurance',
    band: 'open-to-most',
    note: 'Selected on motivation and on what you intend to do afterwards, not on grades. Open to 29 countries only; age 35 for an initial master, 45 for an advanced one.',
    coversAr: "الرسوم، ومخصّص معيشة، والسفر، والتأمين",
    noteAr: "الاختيار يقوم على دوافعك وعلى ما تنوي فعله بعد التخرّج، لا على درجاتك. مفتوحة لـ29 دولة فقط، والعمر حتى 35 للماجستير الأول و45 للماجستير المتقدّم.",
    automatic: false,
  },
  {
    id: 'nawa-banach',
    name: 'Banach Scholarship Programme',
    body: 'NAWA, Poland',
    url: 'https://nawa.gov.pl/en/students/foreign-students/the-banach-scholarship-programme',
    cc: 'PL',
    levels: ['master'],
    tier: 'full-ride',
    covers: 'Tuition exemption at a public Polish university plus a monthly stipend',
    band: 'open-to-most',
    note: 'For applicants from developing countries. Studies in Polish or English depending on the programme.',
    coversAr: "إعفاء من الرسوم في جامعة بولندية حكومية، ومخصّص شهري",
    noteAr: "للمتقدّمين من الدول النامية. والدراسة بالبولندية أو الإنجليزية حسب البرنامج.",
    automatic: false,
  },
  {
    id: 'nawa-first-choice',
    name: 'Poland My First Choice',
    body: 'NAWA, Poland',
    url: 'https://nawa.gov.pl/en/students/foreign-students/poland-my-first-choice',
    cc: 'PL',
    levels: ['bachelor'],
    tier: 'full-ride',
    covers: 'Tuition exemption plus a monthly stipend',
    band: 'competitive',
    coversAr: "إعفاء من الرسوم ومخصّص شهري",
    automatic: false,
  },
  {
    id: 'invest-your-talent',
    name: 'Invest Your Talent in Italy',
    body: 'Italian Ministry of Foreign Affairs',
    url: 'https://www.esteri.it/en/servizi-opportunita/opportunita/borse-di-studio/per-cittadini-stranieri/progetti-speciali/invest-your-talent-in-italy/',
    cc: 'IT',
    levels: ['master'],
    tier: 'full-tuition',
    covers: 'Tuition exemption, a stipend of roughly €9,000, and a company internship',
    band: 'competitive',
    window: [3, 5],
    note: 'English-taught master’s in engineering, design, economics and management. Open to a fixed list of countries.',
    coversAr: "إعفاء من الرسوم، ومخصّص يقارب 9,000 يورو، وتدريب في شركة",
    noteAr: "ماجستير بالإنجليزية في الهندسة والتصميم والاقتصاد والإدارة. مفتوحة لقائمة محدّدة من الدول.",
    automatic: false,
  },
  {
    id: 'mtcp-malaysia',
    name: 'Malaysian Technical Cooperation Programme',
    body: 'Ministry of Foreign Affairs, Malaysia',
    url: 'https://mtcp.kln.gov.my/scholarship',
    cc: 'MY',
    levels: ['master'],
    tier: 'full-ride',
    covers: 'Full tuition plus RM3,500 a month',
    band: 'open-to-most',
    window: [1, 3],
    note: 'Master’s only, and open to developing countries on the published list. A CGPA of 3.0 or a second class upper is the stated bar, with no interview published.',
    barNote: 'CGPA 3.0 or Second Class Upper, age up to 45',
    coversAr: "الرسوم كاملة، إضافة إلى 3,500 رينغيت شهريًا",
    noteAr: "ماجستير فقط، ومفتوحة للدول النامية المدرجة في القائمة المنشورة. الحدّ المعلن معدل 3.0 أو تقدير جيد جدًا مرتفع، ولا مقابلة معلنة.",
    barNoteAr: "معدل تراكمي 3.0 أو جيد جدًا مرتفع، والعمر حتى 45",
    automatic: false,
  },
  {
    id: 'erasmus-mundus',
    name: 'Erasmus Mundus Joint Masters',
    body: 'European Education and Culture Executive Agency',
    url: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters-scholarships',
    cc: 'EU',
    levels: ['master'],
    tier: 'full-ride',
    covers: 'Participation costs, travel and visa, and a monthly living allowance for up to 24 months',
    band: 'competitive',
    window: [10, 1],
    note: 'Around 3,000 places across 160-odd programmes, and each consortium ranks its applicants separately — so a mid-tier programme is a genuinely different proposition from the famous ones.',
    coversAr: "تكاليف المشاركة، والسفر والتأشيرة، ومخصّص معيشة شهري حتى 24 شهرًا",
    noteAr: "نحو 3,000 مقعد موزّعة على أكثر من 160 برنامجًا، وكل اتحاد جامعي يرتّب متقدّميه على حدة — ما يجعل برنامجًا متوسّط الشهرة أمرًا مختلفًا تمامًا عن البرامج الشهيرة.",
    automatic: false,
  },
  {
    id: 'ireland-goi-ies',
    name: 'Government of Ireland International Education Scholarship',
    body: 'Higher Education Authority, Ireland',
    url: 'https://hea.ie/policy/internationalisation/goi-ies/',
    cc: 'IE',
    levels: ['master'],
    tier: 'full-tuition',
    covers: 'Full fee waiver plus €10,000 for one year',
    band: 'highly-selective',
    note: 'Sixty awards a year across the whole country.',
    coversAr: "إعفاء كامل من الرسوم، إضافة إلى 10,000 يورو لسنة واحدة",
    noteAr: "ستون منحة في السنة على مستوى البلد كله.",
    automatic: false,
  },

  // ------------------------------------------------------------- genius tier
  // Kept in the index, hidden by default. They are real, and somebody should be
  // able to find them — but putting them in front of an ordinary applicant as
  // though they were a realistic option wastes the evening this site exists to
  // save.
  {
    id: 'chevening',
    name: 'Chevening Scholarships',
    body: 'UK Foreign, Commonwealth and Development Office',
    url: 'https://www.chevening.org/scholarships/',
    cc: 'GB',
    levels: ['master'],
    tier: 'full-ride',
    covers: 'Tuition, living allowance, flights',
    band: 'highly-selective',
    window: [8, 11],
    note: 'Requires two years of work experience — 2,800 hours — plus leadership essays and an interview.',
    coversAr: "الرسوم، ومخصّص معيشة، وتذاكر الطيران",
    noteAr: "تشترط سنتين من الخبرة العملية — 2,800 ساعة — إضافة إلى مقالات عن القيادة ومقابلة.",
    automatic: false,
  },
  {
    id: 'gates-cambridge',
    name: 'Gates Cambridge Scholarship',
    body: 'University of Cambridge',
    url: 'https://www.gatescambridge.org/apply/',
    cc: 'GB',
    levels: ['master'],
    tier: 'full-ride',
    covers: 'Full cost of studying at Cambridge',
    band: 'highly-selective',
    note: 'Roughly 80 awards a year, worldwide, against tens of thousands of applicants.',
    coversAr: "التكلفة الكاملة للدراسة في كامبريدج",
    noteAr: "نحو 80 منحة سنويًا على مستوى العالم، يتنافس عليها عشرات الآلاف.",
    automatic: false,
  },
]

/** Programme ids that should never appear unless the visitor asks for them. */
export const HIDDEN_BY_DEFAULT = new Set(
  PROGRAMMES.filter((p) => p.band === 'highly-selective').map((p) => p.id)
)
